### ISSUE TITLE
Problem statement/Solution description missing

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [skotcharat/doforfund#1]
@skotcharat Is your most current readme.md pushed? It only shows this: 
<img width="1680" alt="Screen Shot 2020-09-15 at 7 41 27 AM" src="https://user-images.githubusercontent.com/13874466/93211510-f5084800-f726-11ea-87f7-84b4fd8e0249.png">

It should have a description of the problem you are solving and an explanation of how your project will solve that problem.

**Comment by skotcharat** [comment]
@pawaitemadisoncollege I just added Problem statement/Solution description.

**Comment by pawaitemadisoncollege** [comment]
This is a good start. I think we can tweak some of the verbiage, but for the first draft, it is good!
