### ISSUE TITLE
checkpoint 1 is ready for review

### ISSUE THREAD

**Issue by skotcharat** [skotcharat/doforfund#2]
@pawaitemadisoncollege - checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
@skotcharat Ying! You've done a really nice job here! I love the improvements that you made to your problem statement. This explains your project much better.

- [x] Update your project plan for _your_ project. Replace references to trails with the aspects of your project that you will be building! Use your user stories and jsps to define the pieces you will need to build. 
- [x] Double check your screens and flow to be sure all user stories are capture. For example, I see the flow for editing a profile, but I don't think this is listed in the user stories.
- [x] You've covered _create_ and _read_ in your user stories. Make sure you include _edit_ and _delete_ scenarios - these are required for the project. 
- [x] You mentioned in admin user in the readme.md - what will the admin be able to do? Add user stories for the admin.
- [x] I see a way for a user to sign up for an event. How will new events be added into the system? How will photos be added into the system? 
- [x] nav bar: "How it Work" should be "How it Works"
