### ISSUE TITLE
checkpoint 2 ready for review

### ISSUE THREAD

**Issue by skotcharat** [skotcharat/doforfund#8]
@pawaitemadisoncollege checkpoint 2 is complete. I just design to put the column of the picture in the event table. So, every time the admin creates an event the picture will be added, and the user can search for its link to the event table. Is it a good idea?

**Comment by pawaitemadisoncollege** [comment]
@skotcharat You have done a really nice job making consistent progress on your project. That's what checkpoint 2 is really about - keep up that hard work!

A few questions and items to consider:
- [x] Where will images for the gallery be stored? One of the user stories is about searching the gallery?
- [x] If an event only ever has a single image, I think it is ok to leave it on the event table. But if there is going to be a table of gallery images, then maybe it makes sense to put the event image in the gallery table and then store the image id on the event table?
- [x] Be sure to replace any printlns and stacktraces with log statements. https://github.com/skotcharat/doforfund/blob/9f211c629f2db5fcee215bbf371a8952f1ec03a1/src/test/java/edu.matc.test.util/Database.java#L44-L48 and https://github.com/skotcharat/doforfund/blob/9f211c629f2db5fcee215bbf371a8952f1ec03a1/src/test/java/edu.matc.test.util/Database.java#L81

**Comment by skotcharat** [comment]
@pawaitemadisoncollege creates a gallery table that links to the event table makes more sense. Thank you very much
