### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by jtschiss** [skotcharat/doforfund#9]
# Design/Code Review 1
​
## Project: doforfund
​
### Developer: Kotchart
​
### Reviewer: Joah
​
|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Your problem statement explained fairly well. Like the idea of group photography to make it more efficient and affordable. Great idea putting ideas for future expantion |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | I like the simplicity of the layout. Looking at the flow it seems like they have to sign in before they can get to the home page. Is that that something you meant to do?  |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|Couldn't get to the model |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.  | Everything looks good to me |

**Comment by pawaitemadisoncollege** [comment]
@jtschiss Did you search for and find any println and stacktrace statements?

**Comment by skotcharat** [comment]
@jtschiss Actually I am planning to make a user sign in when they want to make a donation for the record and sign in the event. Other people can check out the event before sign in as well.
